set shell := ["sh", "-c"]
set unstable := true

BUILD_DIR := "builddir"
ENTRY_POINT := "src/Main.hs"
EXE := "blog-generator"

default:
  @just --list

build:
  ghc --make -Wall -outputdir {{BUILD_DIR}} -O -o {{BUILD_DIR}}/{{EXE}} src/{*/*.hs,*.hs}

run: build
  ./{{BUILD_DIR}}/{{EXE}}

open: build
  ./{{BUILD_DIR}}/{{EXE}} > index.html
  xdg-open index.html
